[project]
name = "contacts"
version = "0.1.0"
description = "A basic contact manager"
dependencies = [
    "flask",
    "pytest-bdd",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"